version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dev
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306

  app:
    build: .
    container_name: app
    image: app
    environment:
      MYSQL_URL: 'root:123456@tcp(mysql:3306)/dev?charset=utf8&parseTime=True&loc=Local'
    ports:
      - 8080:8080
    depends_on:
      - mysql

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

# volumes:
#   my-data: ./db
